In [1]:
import numpy as np # import 라이브러리 불러오는 명령어

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [2]:
%timeit my_list2 = [i * 2 for i in my_list] # %timeit : 얼만큼 시간이 걸리는지 측정
%timeit my_array2 = my_array * 2

64.1 ms ± 6.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.18 ms ± 365 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a) # 각각 아이템으로 곱셈 연산
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [4]:
# 0차원 : 스칼라(scala), 1차원 : 벡터(vector), 2차원 : 행렬(matrix), 3차원이상: 텐서(tenser)
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [6]:
print(data.shape) # 가로(가장 큰 단위의 배열의 개수), 세로(그 배열 속 배열의 개수)의 길이
print(data.dtype) # 안에 있는 데이터의 세부데이터

(2, 3)
float64


In [10]:
ab = [[[1, 2, 3], [2, 3, 4], [1.2, 3, 0]], [-123, 123, 0]]
abc = np.array(ab, dtype=object) # 불균일한 데이터 형식(가로와 세로의 길이가 다른 데이터)으로 변환 시 옵션으로 dtype=object를 넣어야함, 밑에 또 나옴
print(abc.shape)

(2, 3)


# ndarray 생성하기

In [12]:
data1 = [1, 2, 3, 4, 5] # 리스트에 데이터를 담고
arr1 = np.array(data1) # np.array 
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [3]:
# 배열의 차원 수를 알려줌
print(arr1.ndim) # 1차원
print(arr2.ndim) # 2차원

2

In [4]:
# print(arr1.shape)
arr2.shape

(2, 2)

In [9]:
# print(type(np.zeros(10))) # 데이터는 모르지만 배열의 규격 정함
# print([0] * 10) # 위와 같은 코드라 생각
np.zeros((5, 5)) # np.zeros안에 튜플()을 넣음
# print(np.empty((2, 2, 2))) # zeros와 같다고 생각

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.arange(10) # 0부터 9까지의 순서가 있는 배열을 만들어줌

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## ndarray 자료형

In [24]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # 직접 데이터유형을 바꿈
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [26]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64) # 형변환 함수
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [28]:
arr2 = np.array([1.1, 2.2, 3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype) # 소수를 정수로 형변환 할 때 소수점은 버림처리

float64
[1 2 3]
int64


## 산술 연산

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2*3배열
print(arr)

[[1 2 3]
 [4 5 6]]


In [34]:
print(arr * arr) # 같은 위치에 있는 값끼리 곱셈
print(arr + arr) 
print(1 / arr)
print(arr ** 3) # 모든 데이터들을 세제곱
print(arr - 1)

[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]
[[0 1 2]
 [3 4 5]]


In [39]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2) # 같은 위치에 있는 데이터끼리 비교
print(arr == 3) # 데이터가 3인 데이터를 찾음

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인(indexing)과 슬라이싱(slicing)

In [10]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr[7]
# print(arr[2:5]) # 2번째 데이터부터 4번째 데이터까지 출력

np.int64(7)

In [44]:
arr[2:5] = 10 # 2번째부터 4번째까지 데이터의 값을 10을 변경, 원본도 바뀜
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [12]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop() # 원본을 복제해서 사용했기 때문에 원본은 바뀌지 않음
# print(py_list)

3

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [50]:
print(arr[1][1])
print(arr[1, 1]) # 위와 같음

5
5


In [52]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
                  [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])

In [57]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [65]:
print(arr3d[:1, 1:, 2:])
print(arr3d[0, 1:, 2:]) # 인덱싱 접근을 하면 차원 안으로 들어가기 때문에 차원을 유지하지 않고 차원을 줄여줌

[[[6]
  [9]]]
[[6]
 [9]]


In [66]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택
- 불리언 : 참(True)과 거짓(False) 중 하나의 값을 가짐

In [67]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [68]:
names == 'hong'

array([ True, False,  True, False])

In [70]:
# 전체 데이터 중에서 내가 취하고싶은(특정 조건에 맞는) 데이터를 고를 때 사용
# data[[True, False, True, False]]
data[names == 'hong'] # 트루 위치의 값만 출력

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [73]:
print(data[names == 'hong', 1]) # 인덱스 접근
print(data[names == 'hong', :1]) # 슬라이싱

['60' '70']
[['math']
 ['eng']]


In [77]:
print(names != 'hong') # != 다른가요?
print(~(names == 'hong')) # 계산결과를 역 취해줌

[False  True False  True]
[False  True False  True]


In [78]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)

In [83]:
arr = np.zeros((8, 4)) # 8*4
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [85]:
arr[[4, 3, 0, 5]] # [](인덱싱)안에 [](리스트)를 넣으면 원하는 행을 직접적으로 선택하여 출력, 순서도 지정한대로 출력

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [86]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [91]:
arr = np.arange(32).reshape(8, 4) # 가지고 있는 행렬의 가로세로를 변경할 떄 사용
# print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [96]:
print(arr[[1, 5]])
print(arr[[1, 5], [2, 3]])
print(arr[[1, 5]][:, [2, 3]])

[[ 4  5  6  7]
 [20 21 22 23]]
[ 6 23]
[[ 6  7]
 [22 23]]


## 배열 전치

In [97]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [98]:
print(arr.T) # 행과 열을 바꿈, 대각선을 기준으로 대칭되어 바뀜

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [101]:
# 행렬의 내적, 행렬의 곱 : @ 또는 np.dot사용
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [10]:
samples = np.random.standard_normal(size=(3, 3)) # 랜덤하게 배열을 만들 때 
# samples = np.random.randn(3, 3)
print(samples)

[[-0.9996621  -0.43533094 -0.27068402]
 [ 0.49346028  0.05255746 -1.3617273 ]
 [ 0.44418469 -0.1028652  -0.36184846]]


In [11]:
arr1 = np.sqrt(samples) # nan(not a number) : 숫자가 아님, none이랑 비슷
print(arr1)

[[       nan        nan        nan]
 [0.70246728 0.22925415        nan]
 [0.66647182        nan        nan]]


C:\Users\1-13\AppData\Local\Temp\ipykernel_10860\3462938717.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples) # nan(not a number) : 숫자가 아님, none이랑 비슷


In [12]:
arr2 = np.abs(samples)
print(arr2)

[[0.9996621  0.43533094 0.27068402]
 [0.49346028 0.05255746 1.3617273 ]
 [0.44418469 0.1028652  0.36184846]]


In [106]:
np.isnan(arr1) # 배열안에 nan인 값이 있나요?

array([[False,  True, False],
       [False,  True, False],
       [False, False, False]])